server:
  port: 9009
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: project-sms
  rabbitmq:
    host: 192.168.2.129

aliyun:
  sms:
    accessKeyId : LTAIQrRIoVEpyVZP
    accessKeySecret : PDIU7XweYy4uS9Die3663AfzkA2WcU
    templateCode: SMS_163845970
    signName: 蓝桥电商实训项目